application:
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  security:
    jwt:
      expiration: 10000
      secret-key: 123
server:
  port: 8090
spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/inventario-db
    username: postgres
  graphql:
    graphiql:
      enabled: true
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-doc.html
